# Generated by Django 5.0.7 on 2024-12-04 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_person_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
