# Generated by Django 5.0.7 on 2024-12-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkin_date',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='checkout_date',
            field=models.CharField(max_length=15),
        ),
    ]
