# Generated by Django 5.0.7 on 2024-12-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_order_checkin_date_alter_order_checkout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkin_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='checkout_date',
            field=models.CharField(max_length=10),
        ),
    ]
