# Generated by Django 5.0.7 on 2024-12-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_order_checkin_date_alter_order_checkout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='select_package',
            field=models.CharField(blank=True, choices=[('mombasa', 'Mombasa Value'), ('diani', 'Diani Classic'), ('malindi', 'Malindi Deluxe'), ('bugdets', 'Bugdets Safari'), ('mid-range', 'Mid-Range Safari'), ('luxury', 'Luxury Safari'), ('meru', 'Meru Value'), ('nyeri', 'Nyeri Comfort'), ('nanyuki', 'Nanyuki Exclusive')], max_length=100),
        ),
    ]
