# Generated by Django 5.0.7 on 2024-12-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_order_select_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_number',
            field=models.IntegerField(max_length=15),
        ),
    ]
