# Generated by Django 5.0.7 on 2024-12-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_worker_status_salary_alter_worker_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
